### ISSUE TITLE
Publish on F-Droid


### ISSUE THREAD

**Issue by Wojtaz0w** [vendetta-mod/VendettaManager#52]
Alternatively on IzzyOnDroid repo (if og's too restrictive)

**Comment by DEFCON001** [comment]
This would helps so much lol

**Comment by wingio** [comment]
i don't see any benefits to putting manager on fdroid

**Comment by DEFCON001** [comment]
> i don't see any benefits to putting manager on fdroid

A large number of the issues for this project are install issues, standardizing the install a bit and automating it might help fix a lot of the install issues, and f-droid may (I don't know if it actually would do this though) output errors when something goes wrong, rather than apks just not installing, or freezing during install and giving no output without hooking up adb to debug stuff (which casual users shouldn't have to do). It would also mean that Manager wouldn't need to update itself (which seems to have caused issues in this project too), instead being updated externally by something dedicated to updating and installing apps, with which there is also a larger community to help debug install issues, taking stress off this project which seems to be overflowing with install issues of various causes. Also even hosting on IzzyOnDroid opens you up to a much larger audience stumbling across the app in f-droid when they search discord, as well as smoothing out the install process and making it easier for new users to do.

**Comment by riivx** [comment]
no benefits still, you aren't even sure in half of the things you're talking about + fdroid won't help with logs (install issues now only related to device/rom/manager, add fdroid to that)
